### ISSUE TITLE
Container for openldap

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-containers#1]
see SURFscz/SRAM-deply#469

Build a container to run openldap.

**Comment by mrvanes** [comment]
https://hub.docker.com/r/bitnami/openldap ?
https://github.com/bitnami/containers/blob/main/bitnami/openldap/2.6/debian-11/Dockerfile

**Comment by baszoetekouw** [comment]
Lijkt me prima.  Kun je dat ook in de repo opnemen als een `sram-ldap` subdir met bijbehorende makefile enzo?
