### ISSUE TITLE
Move sram-server container to SBS repo

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-containers#7]
I think we should try and keep the two SBS container in the same repo, as there are dependencies between them and they might need to be updated in sync.  Therefore, please move the sbs-server container config and build to the SBS repo.

This also means that we should probably move the Apache server config from https://github.com/SURFscz/SRAM-deploy/blob/feature-dockerhost/roles/docker_sbs/templates/sbs-apache.j2 to the container.  The only varable we use there are the name of the SBS container and the external hostname of SBS, both of which can be easily set via docker env vars.

**Comment by mrvanes** [comment]
Currently there is one leading _Dockerfile_ for SBS, building SBS image. We can separate the server build in a different directory (`context`) or add a new _Dockerfile_ (eg _Dockerfile-server_) in the root for the server (`file`).
Bonus points: Does this change warrant a new _context_ directory for both _Dockerfiles_, to keep the root clean?

https://github.com/docker/build-push-action?tab=readme-ov-file#customizing

**Comment by mrvanes** [comment]
https://github.com/SURFscz/SBS/pull/1168
Needs https://github.com/SURFscz/SRAM-containers/pull/8

**Comment by mrvanes** [comment]
Also, need to remov SRAM-containers from Action Access
https://github.com/orgs/SURFscz/packages/container/sram-sbs-server/settings

**Comment by baszoetekouw** [comment]
> Also, need to remov SRAM-containers from Action Access https://github.com/orgs/SURFscz/packages/container/sram-sbs-server/settings

Done!
